on:
  push:
    branches:
      - cicd-flow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: ktlint
        run: ./gradlew ktlintCheck

      - name: test
        run: ./gradlew test

      - name: Decode secring.gpg
        run: echo "${{ secrets.SIGNING_SECRET_KEY_RING_FILE_BASE64 }}" | base64 --decode > ./secring.gpg

      - name: build
        run: ./gradlew build

      - name: publish
        run: ./gradlew publishProject
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
