on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: ktlint
        run: ./gradlew ktlintCheck
      - name: test
        run: ./gradlew allTests
